apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-09-20T17:53:50Z
  generation: 1
  labels:
    io.kompose.service: hubserver
  name: hubserver
  namespace: default
  resourceVersion: "55068382"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hubserver
  uid: 219c0260-bcfe-11e8-8068-42010a80004c
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hubserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hubserver
    spec:
      containers:
      - image: us.gcr.io/newagent-9575d/hubserver:v1
        imagePullPolicy: Always
        name: hubserver
        ports:
        - containerPort: 3282
          protocol: TCP
        - containerPort: 3282
          protocol: UDP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/dat/storage
          name: task-pv-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-09-20T17:53:50Z
    lastUpdateTime: 2018-09-20T17:53:50Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
