apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-09-20T16:35:42Z
  name: hubserver
  namespace: default
  resourceVersion: "55059102"
  selfLink: /api/v1/namespaces/default/services/hubserver
  uid: 373785de-bcf3-11e8-8068-42010a80004c
spec:
  clusterIP: 10.43.253.243
  externalTrafficPolicy: Cluster
  ports:
  - name: 3282tcp
    nodePort: 31355
    port: 3282
    protocol: TCP
    targetPort: 3282
  - name: websocket
    nodePort: 31356
    port: 40510
    protocol: TCP
    targetPort: 40510
  selector:
    io.kompose.service: hubserver
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.202.3.15
