apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2017-06-15T15:43:31Z
    name: hubserver
    namespace: default
    resourceVersion: "6844"
    selfLink: /api/v1/namespaces/default/services/hubserver
    uid: 626208ee-51e1-11e7-8167-42010a800254
  spec:
    ports:
    - name: "3282tcp"
      nodePort: 31355
      port: 3282
      protocol: TCP
      targetPort: 3282
    - name: "websocket"
      nodePort: 31356
      port: 40510
      protocol: TCP
      targetPort: 40510
    selector:
      io.kompose.service: hubserver
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""